language: swift
os: osx
osx_image: xcode12u
script:
  - swift build
  - swift test --enable-code-coverage
after_success:
  - brew install llvm
  - echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.zshrc
  - ./codecov.sh
  - bash <(curl -s https://codecov.io/bash)