name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: macos-12
    environment: default
    strategy:
      matrix:
        platform: [macOS]
        xcode: [13.2.1, 13.4.1, '14.0']
        # Swift: 5.5.2, 5.6,     5.7  
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: swift test --enable-code-coverage
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/CoreDataRepositoryPackageTests.xctest/Contents/MacOS/CoreDataRepositoryPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
