name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-13
    environment: default
    steps:
      - uses: actions/checkout@v3
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
  test:
    environment: default
    strategy:
      matrix:
        os: [macos-12, macos-13]
        xcode: [13.2.1, 13.4.1, 14.2, 14.3]
        # Swift: 5.5.2, 5.6,     5.7, 5.8
        include:
          - os: macos-12
            xcode: 13.2.1
          - os: macos-12
            xcode: 13.4.1
          - os: macos-13
            xcode: 14.2
          - os: macos-13
            xcode: 14.3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run Tests
        run: swift test --enable-code-coverage
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/CoreDataRepositoryPackageTests.xctest/Contents/MacOS/CoreDataRepositoryPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
